import React, { useEffect, useRef, useState } from 'react'
import { Pause, Play } from 'lucide-react'

interface LandingHeroMediaProps {
  videoSrc?: string
}

/** The real parish photograph always remains the first paint and video fallback. */
export function LandingHeroMedia({ videoSrc }: LandingHeroMediaProps) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const [canLoadVideo, setCanLoadVideo] = useState(false)
  const [videoReady, setVideoReady] = useState(false)
  const [videoFailed, setVideoFailed] = useState(false)
  const [userPaused, setUserPaused] = useState(false)

  useEffect(() => {
    const video = videoRef.current
    if (!video || !videoSrc) return

    const motion = window.matchMedia?.('(prefers-reduced-motion: reduce)')
    const connection = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection
    if (connection?.saveData) return

    let inView = false
    const syncPlayback = () => {
      if (motion?.matches || !inView || userPaused || document.visibilityState !== 'visible') {
        video.pause()
        return
      }
      setCanLoadVideo(true)
      if (canLoadVideo && !videoFailed) {
        void video.play().catch(() => {
          // The photograph stays visible when the browser declines autoplay.
          setVideoFailed(true)
        })
      }
    }

    const observer = new IntersectionObserver(([entry]) => {
      inView = !!entry?.isIntersecting
      syncPlayback()
    }, { threshold: 0.08 })

    observer.observe(video)
    motion?.addEventListener('change', syncPlayback)
    document.addEventListener('visibilitychange', syncPlayback)
    syncPlayback()
    return () => {
      observer.disconnect()
      motion?.removeEventListener('change', syncPlayback)
      document.removeEventListener('visibilitychange', syncPlayback)
      video.pause()
    }
  }, [canLoadVideo, userPaused, videoFailed, videoSrc])

  return (
    <div className="landing-hero-media absolute inset-0" aria-hidden="false">
      {/* Generated by tools/generate-landing-media.mjs. The source frame carries a printed
          banner across the top, and a phone's hero box is tall enough that object-cover
          always shows the full image height — so that banner was visible on every mobile
          load and no object-position could hide it. The variants are cropped (top 5%) and
          carry AVIF/WebP/JPEG at 640/828/1280/1600/2480: 828w is 38KB as AVIF, and the
          1600w JPEG fallback is 141KB, inside the plan's 70KB mobile / 150KB desktop
          budget. Intrinsic size is the *cropped* 2480x1674, and it is what the width/height
          attributes must carry or the image will not reserve its box.

          sizes is a FIXED choice above 828px, not `100vw`: with 100vw the browser's
          candidate selection wobbled while the route mounted (measured: a cold desktop
          load fetched hero-1600.avif, re-selected hero-2480.avif mid-load — 322KB for a
          1430px box, LCP 2.07s on localhost), while an identical clone appended after
          layout settled always picked 1600w. A constant sizes makes the selection a pure
          function of the viewport, so it can never be re-evaluated, and index.html can
          preload exactly the candidate the img will pick. 1600w still covers every box
          ≤1600px; larger desktops upscale 1.2–1.6× under a dark scrim, which no reader
          can see. */}
      <picture>
        <source
          type="image/avif"
          srcSet="/images/hero/hero-640.avif 640w, /images/hero/hero-828.avif 828w, /images/hero/hero-1280.avif 1280w, /images/hero/hero-1600.avif 1600w, /images/hero/hero-2480.avif 2480w"
          sizes="(max-width: 828px) 100vw, 1600px"
        />
        <source
          type="image/webp"
          srcSet="/images/hero/hero-640.webp 640w, /images/hero/hero-828.webp 828w, /images/hero/hero-1280.webp 1280w, /images/hero/hero-1600.webp 1600w, /images/hero/hero-2480.webp 2480w"
          sizes="(max-width: 828px) 100vw, 1600px"
        />
        <img
          src="/images/hero/hero-1280.jpeg"
          srcSet="/images/hero/hero-640.jpeg 640w, /images/hero/hero-828.jpeg 828w, /images/hero/hero-1280.jpeg 1280w, /images/hero/hero-1600.jpeg 1600w, /images/hero/hero-2480.jpeg 2480w"
          sizes="(max-width: 828px) 100vw, 1600px"
          alt="Tập thể huynh trưởng và thiếu nhi Xứ Đoàn Đức Mẹ Fatima, Giáo Xứ Gia Tôn chụp ảnh lưu niệm trước thánh đường"
          width={2480}
          height={1674}
          decoding="async"
          fetchPriority="high"
          className="scene-hero-bg landing-hero-photo absolute inset-0 w-full h-full object-cover object-center"
        />
      </picture>
      {videoSrc && !videoFailed && (
        <video
          ref={videoRef}
          className="landing-hero-video absolute inset-0 w-full h-full object-cover"
          aria-hidden="true"
          tabIndex={-1}
          muted
          playsInline
          loop
          preload="none"
          poster="/images/hero/hero-1280.jpeg"
          src={canLoadVideo ? videoSrc : undefined}
          data-ready={videoReady}
          onPlaying={() => setVideoReady(true)}
          onError={() => setVideoFailed(true)}
        />
      )}
      {videoSrc && videoReady && !videoFailed && <button
        type="button"
        className="landing-video-control"
        aria-label={userPaused ? 'Phát video Xứ Đoàn' : 'Tạm dừng video Xứ Đoàn'}
        onClick={() => setUserPaused(value => !value)}
      >{userPaused ? <Play aria-hidden="true" /> : <Pause aria-hidden="true" />}</button>}
    </div>
  )
}
