import { Hono } from 'hono'
import { authMiddleware, roleMiddleware, type JwtPayload } from '../middleware/auth.js'
import { successResponse, errorResponse } from '../utils/response.js'
import { reportingApplicationService } from '../services/ReportingApplicationService.js'
import { normalizeAcademicYear } from '../utils/academicYear.js'
import { generatePDFFromHTML, closeBrowser } from '../services/pdfService.js'

const reportingRouter = new Hono()
reportingRouter.use('*', authMiddleware)

/**
 * R4 Endpoint: GET /api/reports/report-card/:studentId
 * Read-Only CQRS Student Report Card Projection
 */
reportingRouter.get('/report-card/:studentId', roleMiddleware('admin', 'chunhiem', 'phuta', 'phuhuynh'), async (c) => {
  const user = c.get('user') as JwtPayload
  const studentId = c.req.param('studentId')
  const academicYear = normalizeAcademicYear(c.req.query('academicYear'))

  try {
    const reportCard = await reportingApplicationService.getStudentReportCard(user, studentId, academicYear)
    if (!reportCard) {
      return errorResponse(c, 'NOT_FOUND', 'Không tìm thấy phiếu điểm của thiếu nhi', 404)
    }

    return successResponse(c, reportCard)
  } catch (err: any) {
    const status = err.status || err.statusCode || 400
    const code = status === 403 ? 'FORBIDDEN' : 'REPORT_GENERATION_ERROR'
    return errorResponse(c, code, err.message || 'Lỗi khi tạo phiếu điểm', status)
  }
})

/**
 * R4 Endpoint: GET /api/reports/class-summary/:classId
 * Read-Only CQRS Class Academic & Attendance Summary
 */
reportingRouter.get('/class-summary/:classId', roleMiddleware('admin', 'chunhiem'), async (c) => {
  const user = c.get('user') as JwtPayload
  const classId = c.req.param('classId')
  const academicYear = normalizeAcademicYear(c.req.query('academicYear'))

  try {
    const classSummary = await reportingApplicationService.getClassSummary(user, classId, academicYear)
    if (!classSummary) {
      return errorResponse(c, 'NOT_FOUND', 'Không tìm thấy báo cáo tổng hợp lớp', 404)
    }

    return successResponse(c, classSummary)
  } catch (err: any) {
    const status = err.status || err.statusCode || 400
    const code = status === 403 ? 'FORBIDDEN' : 'REPORT_GENERATION_ERROR'
    return errorResponse(c, code, err.message || 'Lỗi khi tạo báo cáo tổng hợp lớp', status)
  }
})

/**
 * POST /api/reports/generate-pdf
 * Generate PDF from HTML content (server-side via Puppeteer)
 * Body: { htmlContent: string, options?: { format?: 'A4'|'A3'|'Letter', landscape?: boolean, margin?: {...} } }
 */
reportingRouter.post('/generate-pdf', roleMiddleware('admin', 'chunhiem', 'phuta'), async (c) => {
  try {
    const body = await c.req.json()
    const { htmlContent, options } = body

    if (!htmlContent || typeof htmlContent !== 'string') {
      return errorResponse(c, 'BAD_REQUEST', 'htmlContent là bắt buộc và phải là string', 400)
    }

    // Sanitize HTML content to prevent XSS - only allow safe HTML
    // The HTML is already generated by trusted server-side templates
    const pdfBuffer = await generatePDFFromHTML(htmlContent, options || {})

    return c.body(pdfBuffer, 200, {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="report_${Date.now()}.pdf"`,
      'Content-Length': pdfBuffer.length.toString(),
    })
  } catch (err: any) {
    console.error('[PDF Generation Error]:', err)
    return errorResponse(c, 'PDF_GENERATION_FAILED', err.message || 'Không thể tạo file PDF', 500)
  }
})

// Graceful shutdown for browser
process.on('SIGTERM', async () => {
  await closeBrowser()
})

process.on('SIGINT', async () => {
  await closeBrowser()
})

export default reportingRouter
